package com.beemindz.miyotee.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.beemindz.miyotee.dao.Task;
import com.beemindz.miyotee.dao.TaskDraft;

import com.beemindz.miyotee.dao.TaskDao;
import com.beemindz.miyotee.dao.TaskDraftDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskDaoConfig;
    private final DaoConfig taskDraftDaoConfig;

    private final TaskDao taskDao;
    private final TaskDraftDao taskDraftDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        taskDraftDaoConfig = daoConfigMap.get(TaskDraftDao.class).clone();
        taskDraftDaoConfig.initIdentityScope(type);

        taskDao = new TaskDao(taskDaoConfig, this);
        taskDraftDao = new TaskDraftDao(taskDraftDaoConfig, this);

        registerDao(Task.class, taskDao);
        registerDao(TaskDraft.class, taskDraftDao);
    }
    
    public void clear() {
        taskDaoConfig.getIdentityScope().clear();
        taskDraftDaoConfig.getIdentityScope().clear();
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public TaskDraftDao getTaskDraftDao() {
        return taskDraftDao;
    }

}
